# Generated by Django 5.1.7 on 2025-04-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_episode_options_episode_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='paid',
        ),
        migrations.AddField(
            model_name='course',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
