# Generated by Django 5.2.1 on 2025-08-25 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_comment_course_alter_comment_reply_and_more'),
        ('order', '0002_coupon_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='home.course'),
        ),
    ]
